weights: yolov5s.pt
cfg: ''
data: /content/coin_dataset/coin_dataset.yml
hyp: data/hyp.scratch.yaml
epochs: 250
batch_size: 16
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/train
name: ''
log_imgs: 0
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
